define([], function(){
	var Champions = [{
		"Name": "Ahri",
		"Title": "The Nine-Tailed Fox",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "50",
		"Damage_per_level": "3",
		"Health": "380",
		"Health_Per_level": "80",
		"Mana": "230",
		"Mana_Per_Level": "50",
		"Speed": "305",
		"Range": "550",
		"Attack_Speed": "0.668",
		"AS_Per_Level": "0.0126",
		"Armor": "11",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "5.5",
		"HR_Per_level": "0.6",
		"Mana_regen": "6.25",
		"MRegen_Per_Level": "0.6",
		"Tags": "Assassin, mage, ranged",
		"Champ_Id": "108",
		"Release_Date": "2011-12-14"
	},
	{
		"Name": "Akali",
		"Title": "The Fist of Shadow",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "53",
		"Damage_per_level": "3.2",
		"Health": "445",
		"Health_Per_level": "85",
		"Mana": "200",
		"Mana_Per_Level": "0",
		"Speed": "325",
		"Range": "125",
		"Attack_Speed": "0.694",
		"AS_Per_Level": "0.0215",
		"Armor": "16.5",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.25",
		"HR_Per_level": "0.65",
		"Mana_regen": "50",
		"MRegen_Per_Level": "0",
		"Tags": "Assassin, melee, stealth",
		"Champ_Id": "84",
		"Release_Date": "2010-05-11"
	},
	{
		"Name": "Alistar",
		"Title": "The Minotaur",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "55.03",
		"Damage_per_level": "3.62",
		"Health": "442",
		"Health_Per_level": "102",
		"Mana": "215",
		"Mana_Per_Level": "38",
		"Speed": "305",
		"Range": "125",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.0133",
		"Armor": "14.5",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.25",
		"HR_Per_level": "0.85",
		"Mana_regen": "6.45",
		"MRegen_Per_Level": "0.45",
		"Tags": "Tank, pusher, melee",
		"Champ_Id": "12",
		"Release_Date": "2009-02-21"
	},
	{
		"Name": "Amumu",
		"Title": "The Sad Mummy",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "47",
		"Damage_per_level": "3.8",
		"Health": "472",
		"Health_Per_level": "84",
		"Mana": "220",
		"Mana_Per_Level": "40",
		"Speed": "310",
		"Range": "125",
		"Attack_Speed": "0.638",
		"AS_Per_Level": "0.0138",
		"Armor": "18",
		"Armor_Per_Level": "3.3",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.45",
		"HR_Per_level": "0.85",
		"Mana_regen": "6.50",
		"MRegen_Per_Level": "0.525",
		"Tags": "Tank, melee",
		"Champ_Id": "32",
		"Release_Date": "2009-06-26"
	},
	{
		"Name": "Anivia",
		"Title": "The Cryophoenix",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "48",
		"Damage_per_level": "3.2",
		"Health": "350",
		"Health_Per_level": "70",
		"Mana": "257",
		"Mana_Per_Level": "53",
		"Speed": "300",
		"Range": "600",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.01",
		"Armor": "10.5",
		"Armor_Per_Level": "4",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.65",
		"HR_Per_level": "0.55",
		"Mana_regen": "7.0",
		"MRegen_Per_Level": "0.6",
		"Tags": "Mage, ranged",
		"Champ_Id": "34",
		"Release_Date": "2009-07-10"
	},
	{
		"Name": "Annie",
		"Title": "The Dark Child",
		"Rp_Point": "260",
		"Ip_Point": "450",
		"Damage": "49",
		"Damage_per_level": "2.625",
		"Health": "384",
		"Health_Per_level": "76",
		"Mana": "250",
		"Mana_Per_Level": "50",
		"Speed": "310",
		"Range": "625",
		"Attack_Speed": "0.575",
		"AS_Per_Level": "0.0078",
		"Armor": "8.5",
		"Armor_Per_Level": "4",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.5",
		"HR_Per_level": "0.55",
		"Mana_regen": "6.9",
		"MRegen_Per_Level": "0.6",
		"Tags": "Mage, ranged, recommended",
		"Champ_Id": "1",
		"Release_Date": "2009-02-21"
	},
	{
		"Name": "Ashe",
		"Title": "The Frost Archer",
		"Rp_Point": "260",
		"Ip_Point": "450",
		"Damage": "46.3",
		"Damage_per_level": "2.85",
		"Health": "395",
		"Health_Per_level": "79",
		"Mana": "173",
		"Mana_Per_Level": "35",
		"Speed": "300",
		"Range": "600",
		"Attack_Speed": "0.658",
		"AS_Per_Level": "0.022",
		"Armor": "11.5",
		"Armor_Per_Level": "3.4",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.5",
		"HR_Per_level": "0.55",
		"Mana_regen": "6.3",
		"MRegen_Per_Level": "0.4",
		"Tags": "Carry, ranged, recommended",
		"Champ_Id": "22",
		"Release_Date": "2009-02-21"
	},
	{
		"Name": "Blitzcrank",
		"Title": "The Great Steam Golem",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "55.66",
		"Damage_per_level": "3.5",
		"Health": "468",
		"Health_Per_level": "100",
		"Mana": "260",
		"Mana_Per_Level": "40",
		"Speed": "300",
		"Range": "125",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.007",
		"Armor": "14.5",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.25",
		"HR_Per_level": "0.75",
		"Mana_regen": "6.60",
		"MRegen_Per_Level": "0.50",
		"Tags": "Fighter, melee",
		"Champ_Id": "53",
		"Release_Date": "2009-09-02"
	},
	{
		"Name": "Brand",
		"Title": "The Burning Vengeance",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "51.66",
		"Damage_per_level": "3",
		"Health": "380",
		"Health_Per_level": "76",
		"Mana": "250",
		"Mana_Per_Level": "45",
		"Speed": "315",
		"Range": "550",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.008",
		"Armor": "12",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.5",
		"HR_Per_level": "0.55",
		"Mana_regen": "7.0",
		"MRegen_Per_Level": "0.6",
		"Tags": "Mage, ranged",
		"Champ_Id": "63",
		"Release_Date": "2011-04-12"
	},
	{
		"Name": "Caitlyn",
		"Title": "The Sheriff of Piltover",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "47",
		"Damage_per_level": "3",
		"Health": "390",
		"Health_Per_level": "80",
		"Mana": "255",
		"Mana_Per_Level": "35",
		"Speed": "300",
		"Range": "650",
		"Attack_Speed": "0.668",
		"AS_Per_Level": "0.020",
		"Armor": "13",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.75",
		"HR_Per_level": "0.55",
		"Mana_regen": "6.5",
		"MRegen_Per_Level": "0.55",
		"Tags": "Carry, ranged",
		"Champ_Id": "51",
		"Release_Date": "2011-01-04"
	},
	{
		"Name": "Cassiopeia",
		"Title": "The Serpent's Embrace",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "47",
		"Damage_per_level": "3.2",
		"Health": "380",
		"Health_Per_level": "75",
		"Mana": "250",
		"Mana_Per_Level": "50",
		"Speed": "310",
		"Range": "550",
		"Attack_Speed": "0.647",
		"AS_Per_Level": "0.01085",
		"Armor": "11.5",
		"Armor_Per_Level": "4",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.85",
		"HR_Per_level": "0.50",
		"Mana_regen": "7.10",
		"MRegen_Per_Level": "0.75",
		"Tags": "Mage, ranged",
		"Champ_Id": "69",
		"Release_Date": "2010-12-14"
	},
	{
		"Name": "Cho'Gath",
		"Title": "The Terror of the Void",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "54.1",
		"Damage_per_level": "4.2",
		"Health": "440",
		"Health_Per_level": "80",
		"Mana": "205",
		"Mana_Per_Level": "40",
		"Speed": "320",
		"Range": "125",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.009",
		"Armor": "19",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.5",
		"HR_Per_level": "0.85",
		"Mana_regen": "6.15",
		"MRegen_Per_Level": "0.45",
		"Tags": "Fighter, mage, melee",
		"Champ_Id": "31",
		"Release_Date": "2009-06-26"
	},
	{
		"Name": "Corki",
		"Title": "The Daring Bombardier",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "48.2",
		"Damage_per_level": "3",
		"Health": "375",
		"Health_Per_level": "82",
		"Mana": "243",
		"Mana_Per_Level": "37",
		"Speed": "300",
		"Range": "550",
		"Attack_Speed": "0.658",
		"AS_Per_Level": "0.015",
		"Armor": "13.5",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.5",
		"HR_Per_level": "0.55",
		"Mana_regen": "4.0",
		"MRegen_Per_Level": "0.35",
		"Tags": "Ranged, carry",
		"Champ_Id": "42",
		"Release_Date": "2009-09-19"
	},
	{
		"Name": "Darius",
		"Title": "The Hand of Noxus",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "50",
		"Damage_per_level": "3.5",
		"Health": "426",
		"Health_Per_level": "93",
		"Mana": "200",
		"Mana_Per_Level": "37.5",
		"Speed": "310",
		"Range": "125",
		"Attack_Speed": "0.679",
		"AS_Per_Level": "0.017",
		"Armor": "20",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "8.25",
		"HR_Per_level": "0.95",
		"Mana_regen": "6",
		"MRegen_Per_Level": "0.35",
		"Tags": "Fighter, melee",
		"Champ_Id": "118",
		"Release_Date": "2012-05-23"
	},
	{
		"Name": "Diana",
		"Title": "Scorn of the Moon",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "51",
		"Damage_per_level": "3",
		"Health": "438",
		"Health_Per_level": "90",
		"Mana": "230",
		"Mana_Per_Level": "40",
		"Speed": "320",
		"Range": "150",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.014",
		"Armor": "16",
		"Armor_Per_Level": "3.6",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "8.88",
		"HR_Per_level": "0.12",
		"Mana_regen": "7",
		"MRegen_Per_Level": "0.12",
		"Tags": "Fighter,melee,Mage,jungler",
		"Champ_Id": "122",
		"Release_Date": "2012-08-07"
	},
	{
		"Name": "Dr.Mundo",
		"Title": "The Madman of Zaun",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "56.23",
		"Damage_per_level": "3",
		"Health": "433",
		"Health_Per_level": "89",
		"Mana": "0",
		"Mana_Per_Level": "0",
		"Speed": "320",
		"Range": "125",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.017",
		"Armor": "17",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "6.5",
		"HR_Per_level": "0.75",
		"Mana_regen": "0",
		"MRegen_Per_Level": "0",
		"Tags": "Fighter, melee",
		"Champ_Id": "36",
		"Release_Date": "2009-09-02"
	},
	{
		"Name": "Draven",
		"Title": "The Glorious Executioner",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "46.5",
		"Damage_per_level": "3.5",
		"Health": "420",
		"Health_Per_level": "82",
		"Mana": "240",
		"Mana_Per_Level": "42",
		"Speed": "305",
		"Range": "550",
		"Attack_Speed": "0.679",
		"AS_Per_Level": "0.017",
		"Armor": "16",
		"Armor_Per_Level": "3.3",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "5",
		"HR_Per_level": "0.7",
		"Mana_regen": "6.95",
		"MRegen_Per_Level": "0.65",
		"Tags": "Carry, ranged",
		"Champ_Id": "119",
		"Release_Date": "2012-06-06"
	},
	{
		"Name": "Evelynn",
		"Title": "The Widowmaker",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "48",
		"Damage_per_level": "3.3",
		"Health": "414",
		"Health_Per_level": "86",
		"Mana": "180",
		"Mana_Per_Level": "42",
		"Speed": "315",
		"Range": "125",
		"Attack_Speed": "0.658",
		"AS_Per_Level": "0.0252",
		"Armor": "12.5",
		"Armor_Per_Level": "4",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "6.95",
		"HR_Per_level": "0.55",
		"Mana_regen": "7.1",
		"MRegen_Per_Level": "0.6",
		"Tags": "Assassin, stealth, melee",
		"Champ_Id": "28",
		"Release_Date": "2009-05-01"
	},
	{
		"Name": "Ezreal",
		"Title": "The Prodigal Explorer",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "47.2",
		"Damage_per_level": "3",
		"Health": "350",
		"Health_Per_level": "80",
		"Mana": "235",
		"Mana_Per_Level": "45",
		"Speed": "305",
		"Range": "550",
		"Attack_Speed": "0.665",
		"AS_Per_Level": "0.0185",
		"Armor": "12",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "5.5",
		"HR_Per_level": "0.55",
		"Mana_regen": "7.0",
		"MRegen_Per_Level": "0.65",
		"Tags": "Carry, ranged",
		"Champ_Id": "81",
		"Release_Date": "2010-03-16"
	},
	{
		"Name": "Fiddlesticks",
		"Title": "The Harbinger of Doom",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "45.95",
		"Damage_per_level": "2.625",
		"Health": "390",
		"Health_Per_level": "80",
		"Mana": "251",
		"Mana_Per_Level": "59",
		"Speed": "310",
		"Range": "480",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.0132",
		"Armor": "11",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.6",
		"HR_Per_level": "0.6",
		"Mana_regen": "6.9",
		"MRegen_Per_Level": "0.65",
		"Tags": "Mage, jungler, ranged",
		"Champ_Id": "9",
		"Release_Date": "2009-02-21"
	},
	{
		"Name": "Fiora",
		"Title": "The Grand Duelist",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "54",
		"Damage_per_level": "3.2",
		"Health": "450",
		"Health_Per_level": "85",
		"Mana": "220",
		"Mana_Per_Level": "40",
		"Speed": "325",
		"Range": "125",
		"Attack_Speed": "0.672",
		"AS_Per_Level": "0.019",
		"Armor": "15",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "6.3",
		"HR_Per_level": "0.8",
		"Mana_regen": "7.25",
		"MRegen_Per_Level": "0.5",
		"Tags": "Melee, carry",
		"Champ_Id": "114",
		"Release_Date": "2012-02-29"
	},
	{
		"Name": "Fizz",
		"Title": "The Tidal Trickster",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "56",
		"Damage_per_level": "3",
		"Health": "414",
		"Health_Per_level": "86",
		"Mana": "200",
		"Mana_Per_Level": "40",
		"Speed": "310",
		"Range": "175",
		"Attack_Speed": "0.678",
		"AS_Per_Level": "0.021",
		"Armor": "13",
		"Armor_Per_Level": "3.4",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.0",
		"HR_Per_level": "0.7",
		"Mana_regen": "6.15",
		"MRegen_Per_Level": "0.45",
		"Tags": "Fighter, assassin, melee",
		"Champ_Id": "109",
		"Release_Date": "2011-11-15"
	},
	{
		"Name": "Galio",
		"Title": "The Sentinel's Sorrow",
		"Rp_Point": "975",
		"Ip_Point": "4800",
		"Damage": "56.3",
		"Damage_per_level": "3.375",
		"Health": "435",
		"Health_Per_level": "85",
		"Mana": "235",
		"Mana_Per_Level": "50",
		"Speed": "310",
		"Range": "125",
		"Attack_Speed": "0.638",
		"AS_Per_Level": "0.0075",
		"Armor": "17",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "7.45",
		"HR_Per_level": "0.75",
		"Mana_regen": "7.0",
		"MRegen_Per_Level": "0.7",
		"Tags": "Tank, support, melee",
		"Champ_Id": "3",
		"Release_Date": "2010-08-10"
	},
	{
		"Name": "Gangplank",
		"Title": "The Saltwater Scourge",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "54",
		"Damage_per_level": "3",
		"Health": "495",
		"Health_Per_level": "81",
		"Mana": "215",
		"Mana_Per_Level": "40",
		"Speed": "320",
		"Range": "125",
		"Attack_Speed": "0.651",
		"AS_Per_Level": "0.017",
		"Armor": "16.5",
		"Armor_Per_Level": "3.3",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "4.25",
		"HR_Per_level": "0.75",
		"Mana_regen": "6.5",
		"MRegen_Per_Level": "0.7",
		"Tags": "Carry, melee",
		"Champ_Id": "41",
		"Release_Date": "2009-08-19"
	},
	{
		"Name": "Garen",
		"Title": "The Might of Demacia",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "52.5",
		"Damage_per_level": "3.5",
		"Health": "455",
		"Health_Per_level": "96",
		"Mana": "0",
		"Mana_Per_Level": "0",
		"Speed": "320",
		"Range": "125",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.018",
		"Armor": "19",
		"Armor_Per_Level": "2.7",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.5",
		"HR_Per_level": "0.75",
		"Mana_regen": "0",
		"MRegen_Per_Level": "0",
		"Tags": "Fighter, melee, recommended",
		"Champ_Id": "86",
		"Release_Date": "2010-04-27"
	},
	{
		"Name": "Gragas",
		"Title": "The Rabble Rouser",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "55.78",
		"Damage_per_level": "3.375",
		"Health": "434",
		"Health_Per_level": "89",
		"Mana": "221",
		"Mana_Per_Level": "47",
		"Speed": "315",
		"Range": "125",
		"Attack_Speed": "0.651",
		"AS_Per_Level": "0.0133",
		"Armor": "16",
		"Armor_Per_Level": "3.6",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "7.25",
		"HR_Per_level": "0.85",
		"Mana_regen": "6.45",
		"MRegen_Per_Level": "0.45",
		"Tags": "Fighter, melee",
		"Champ_Id": "79",
		"Release_Date": "2010-02-02"
	},
	{
		"Name": "Graves",
		"Title": "The Outlaw",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "51",
		"Damage_per_level": "3.1",
		"Health": "410",
		"Health_Per_level": "84",
		"Mana": "255",
		"Mana_Per_Level": "40",
		"Speed": "305",
		"Range": "525",
		"Attack_Speed": "0.638",
		"AS_Per_Level": "0.018",
		"Armor": "15",
		"Armor_Per_Level": "3.2",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "5.5",
		"HR_Per_level": "0.7",
		"Mana_regen": "6.75",
		"MRegen_Per_Level": "0.7",
		"Tags": "Carry, ranged",
		"Champ_Id": "105",
		"Release_Date": "2011-10-19"
	},
	{
		"Name": "Hecarim",
		"Title": "The Shadow of War",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "53",
		"Damage_per_level": "3",
		"Health": "440",
		"Health_Per_level": "95",
		"Mana": "210",
		"Mana_Per_Level": "40",
		"Speed": "320",
		"Range": "175",
		"Attack_Speed": "0.67",
		"AS_Per_Level": "0.016",
		"Armor": "16",
		"Armor_Per_Level": "4",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "8",
		"HR_Per_level": "0.75",
		"Mana_regen": "6.5",
		"MRegen_Per_Level": "0.6",
		"Tags": "Fighter, jungler, melee",
		"Champ_Id": "116",
		"Release_Date": "2012-04-18"
	},
	{
		"Name": "Heimerdinger",
		"Title": "The Revered Inventor",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "49.24",
		"Damage_per_level": "3",
		"Health": "350",
		"Health_Per_level": "75",
		"Mana": "240",
		"Mana_Per_Level": "65",
		"Speed": "300",
		"Range": "550",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.0075",
		"Armor": "7",
		"Armor_Per_Level": "3",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.5",
		"HR_Per_level": "0.55",
		"Mana_regen": "7.0",
		"MRegen_Per_Level": "0.65",
		"Tags": "Mage, pusher, ranged",
		"Champ_Id": "74",
		"Release_Date": "2009-10-10"
	},
	{
		"Name": "Irelia",
		"Title": "The Will of the Blades",
		"Rp_Point": "975",
		"Ip_Point": "4800",
		"Damage": "56.3",
		"Damage_per_level": "3.3",
		"Health": "456",
		"Health_Per_level": "90",
		"Mana": "230",
		"Mana_Per_Level": "35",
		"Speed": "320",
		"Range": "125",
		"Attack_Speed": "0.665",
		"AS_Per_Level": "0.021",
		"Armor": "15",
		"Armor_Per_Level": "3.75",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.5",
		"HR_Per_level": "0.65",
		"Mana_regen": "7.0",
		"MRegen_Per_Level": "0.65",
		"Tags": "Assassin, melee",
		"Champ_Id": "39",
		"Release_Date": "2010-11-16"
	},
	{
		"Name": "Janna",
		"Title": "The Storm's Fury",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "49",
		"Damage_per_level": "2.95",
		"Health": "356",
		"Health_Per_level": "78",
		"Mana": "302",
		"Mana_Per_Level": "64",
		"Speed": "310",
		"Range": "475",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.0163",
		"Armor": "9",
		"Armor_Per_Level": "3.8",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.5",
		"HR_Per_level": "0.55",
		"Mana_regen": "6.9",
		"MRegen_Per_Level": "0.60",
		"Tags": "Support, ranged",
		"Champ_Id": "40",
		"Release_Date": "2009-09-02"
	},
	{
		"Name": "Jarvan IV",
		"Title": "the Exemplar of Demacia",
		"Rp_Point": "975",
		"Ip_Point": "4800",
		"Damage": "50",
		"Damage_per_level": "3",
		"Health": "420",
		"Health_Per_level": "90",
		"Mana": "235",
		"Mana_Per_Level": "40",
		"Speed": "315",
		"Range": "175",
		"Attack_Speed": "0.658",
		"AS_Per_Level": "0.0165",
		"Armor": "14",
		"Armor_Per_Level": "3",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.0",
		"HR_Per_level": "0.7",
		"Mana_regen": "6.0",
		"MRegen_Per_Level": "0.45",
		"Tags": "Fighter, melee",
		"Champ_Id": "59",
		"Release_Date": "2011-03-01"
	},
	{
		"Name": "Jax",
		"Title": "Grandmaster at Arms",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "56.3",
		"Damage_per_level": "3.375",
		"Health": "468",
		"Health_Per_level": "98",
		"Mana": "200",
		"Mana_Per_Level": "35",
		"Speed": "325",
		"Range": "125",
		"Attack_Speed": "0.638",
		"AS_Per_Level": "0.022",
		"Armor": "18",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.45",
		"HR_Per_level": "0.55",
		"Mana_regen": "6.4",
		"MRegen_Per_Level": "0.7",
		"Tags": "Fighter, melee",
		"Champ_Id": "24",
		"Release_Date": "2009-02-21"
	},
	{
		"Name": "Jayce",
		"Title": "The Defender of Tomorrow",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "46.5",
		"Damage_per_level": "3.5",
		"Health": "420",
		"Health_Per_level": "90",
		"Mana": "240",
		"Mana_Per_Level": "40",
		"Speed": "310",
		"Range": "125",
		"Attack_Speed": "0.658",
		"AS_Per_Level": "0.017",
		"Armor": "13",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "6.0",
		"HR_Per_level": "0.8",
		"Mana_regen": "7.0",
		"MRegen_Per_Level": "0.7",
		"Tags": "Fighter, melee, ranged",
		"Champ_Id": "120",
		"Release_Date": "2012-07-07"
	},
	{
		"Name": "Karma",
		"Title": "The Enlightened One",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "50",
		"Damage_per_level": "3.3",
		"Health": "410",
		"Health_Per_level": "86",
		"Mana": "240",
		"Mana_Per_Level": "60",
		"Speed": "310",
		"Range": "425",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.0145",
		"Armor": "15",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.7",
		"HR_Per_level": "0.55",
		"Mana_regen": "6.8",
		"MRegen_Per_Level": "0.65",
		"Tags": "Support, ranged",
		"Champ_Id": "43",
		"Release_Date": "2011-02-01"
	},
	{
		"Name": "Karthus",
		"Title": "The Deathsinger",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "42.2",
		"Damage_per_level": "3.25",
		"Health": "390",
		"Health_Per_level": "75",
		"Mana": "270",
		"Mana_Per_Level": "61",
		"Speed": "310",
		"Range": "450",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.0132",
		"Armor": "11",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "5.5",
		"HR_Per_level": "0.55",
		"Mana_regen": "6.5",
		"MRegen_Per_Level": "0.6",
		"Tags": "Mage, ranged",
		"Champ_Id": "30",
		"Release_Date": "2009-06-12"
	},
	{
		"Name": "Kassadin",
		"Title": "The Void Walker",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "52.3",
		"Damage_per_level": "3.9",
		"Health": "433",
		"Health_Per_level": "78",
		"Mana": "230",
		"Mana_Per_Level": "45",
		"Speed": "315",
		"Range": "125",
		"Attack_Speed": "0.640",
		"AS_Per_Level": "0.0235",
		"Armor": "14",
		"Armor_Per_Level": "3.2",
		"Magic_Resistance": "6.9",
		"MR_Per_level": "0.6",
		"Health_Regen": "6.95",
		"HR_Per_level": "0.5",
		"Mana_regen": "6.9",
		"MRegen_Per_Level": "0.6",
		"Tags": "Assassin, mage, melee",
		"Champ_Id": "38",
		"Release_Date": "2009-08-07"
	},
	{
		"Name": "Katarina",
		"Title": "The Sinister Blade",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "53",
		"Damage_per_level": "3.2",
		"Health": "395",
		"Health_Per_level": "83",
		"Mana": "0",
		"Mana_Per_Level": "0",
		"Speed": "325",
		"Range": "125",
		"Attack_Speed": "0.658",
		"AS_Per_Level": "0.018",
		"Armor": "14.75",
		"Armor_Per_Level": "4",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "6.95",
		"HR_Per_level": "0.55",
		"Mana_regen": "0",
		"MRegen_Per_Level": "0",
		"Tags": "Assassin, melee, recommended",
		"Champ_Id": "55",
		"Release_Date": "2009-09-19"
	},
	{
		"Name": "Kayle",
		"Title": "The Judicator",
		"Rp_Point": "260",
		"Ip_Point": "450",
		"Damage": "53.3",
		"Damage_per_level": "2.8",
		"Health": "418",
		"Health_Per_level": "93",
		"Mana": "255",
		"Mana_Per_Level": "40",
		"Speed": "310",
		"Range": "125",
		"Attack_Speed": "0.638",
		"AS_Per_Level": "0.015",
		"Armor": "17",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "0.75",
		"Health_Regen": "7.0",
		"HR_Per_level": "0.75",
		"Mana_regen": "6.9",
		"MRegen_Per_Level": "0.525",
		"Tags": "Fighter, support",
		"Champ_Id": "10",
		"Release_Date": "2009-02-21"
	},
	{
		"Name": "Kennen",
		"Title": "The Heart of the Tempest",
		"Rp_Point": "975",
		"Ip_Point": "4800",
		"Damage": "51.3",
		"Damage_per_level": "3.3",
		"Health": "403",
		"Health_Per_level": "79",
		"Mana": "200",
		"Mana_Per_Level": "0",
		"Speed": "310",
		"Range": "550",
		"Attack_Speed": "0.690",
		"AS_Per_Level": "0.0245",
		"Armor": "14",
		"Armor_Per_Level": "3.75",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.65",
		"HR_Per_level": "0.65",
		"Mana_regen": "50",
		"MRegen_Per_Level": "0",
		"Tags": "Mage, ranged",
		"Champ_Id": "85",
		"Release_Date": "2010-04-08"
	},
	{
		"Name": "Kog'Maw",
		"Title": "The Mouth of the Abyss",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "46",
		"Damage_per_level": "3",
		"Health": "440",
		"Health_Per_level": "84",
		"Mana": "295",
		"Mana_Per_Level": "40",
		"Speed": "305",
		"Range": "500",
		"Attack_Speed": "0.665",
		"AS_Per_Level": "0.017",
		"Armor": "13",
		"Armor_Per_Level": "3.53",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "5",
		"HR_Per_level": "0.55",
		"Mana_regen": "7.5",
		"MRegen_Per_Level": "0.7",
		"Tags": "Ranged, carry",
		"Champ_Id": "96",
		"Release_Date": "2010-06-24"
	},
	{
		"Name": "LeBlanc",
		"Title": "The Deceiver",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "51",
		"Damage_per_level": "3.1",
		"Health": "390",
		"Health_Per_level": "75",
		"Mana": "250",
		"Mana_Per_Level": "50",
		"Speed": "310",
		"Range": "525",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.0085",
		"Armor": "12",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.5",
		"HR_Per_level": "0.55",
		"Mana_regen": "6.9",
		"MRegen_Per_Level": "0.6",
		"Tags": "Assassin, mage, ranged",
		"Champ_Id": "7",
		"Release_Date": "2010-11-02"
	},
	{
		"Name": "Lee Sin",
		"Title": "The Blind Monk",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "55.8",
		"Damage_per_level": "3.2",
		"Health": "428",
		"Health_Per_level": "85",
		"Mana": "200",
		"Mana_Per_Level": "0",
		"Speed": "325",
		"Range": "125",
		"Attack_Speed": "0.651",
		"AS_Per_Level": "0.019",
		"Armor": "16",
		"Armor_Per_Level": "3.7",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "6.258",
		"HR_Per_level": "0.7",
		"Mana_regen": "50",
		"MRegen_Per_Level": "0",
		"Tags": "Assassin, melee",
		"Champ_Id": "64",
		"Release_Date": "2011-04-01"
	},
	{
		"Name": "Leona",
		"Title": "The Radiant Dawn",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "55",
		"Damage_per_level": "3",
		"Health": "430",
		"Health_Per_level": "87",
		"Mana": "235",
		"Mana_Per_Level": "40",
		"Speed": "310",
		"Range": "125",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.029",
		"Armor": "18",
		"Armor_Per_Level": "3.1",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "9.0",
		"HR_Per_level": "0.85",
		"Mana_regen": "8.0",
		"MRegen_Per_Level": "0.70",
		"Tags": "Tank, melee",
		"Champ_Id": "89",
		"Release_Date": "2011-07-13"
	},
	{
		"Name": "Lulu",
		"Title": "The Fae Sorceress",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "44.4",
		"Damage_per_level": "2.6",
		"Health": "415",
		"Health_Per_level": "82",
		"Mana": "200",
		"Mana_Per_Level": "50",
		"Speed": "300",
		"Range": "550",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.013",
		"Armor": "9",
		"Armor_Per_Level": "3.7",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "6.0",
		"HR_Per_level": "0.72",
		"Mana_regen": "6.0",
		"MRegen_Per_Level": "0.6",
		"Tags": "Ranged, support",
		"Champ_Id": "115",
		"Release_Date": "2012-03-20"
	},
	{
		"Name": "Lux",
		"Title": "The Lady of Luminosity",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "50",
		"Damage_per_level": "3.3",

		"Health": "345",
		"Health_Per_level": "79",
		"Mana": "250",
		"Mana_Per_Level": "50",
		"Speed": "315",
		"Range": "550",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.0085",
		"Armor": "8",
		"Armor_Per_Level": "4",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.5",
		"HR_Per_level": "0.55",
		"Mana_regen": "6.0",
		"MRegen_Per_Level": "0.6",
		"Tags": "Mage, support, ranged",
		"Champ_Id": "99",
		"Release_Date": "2010-10-19"
	},
	{
		"Name": "Malphite",
		"Title": "Shard of the Monolith",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "56.3",
		"Damage_per_level": "3.375",
		"Health": "423",
		"Health_Per_level": "90",
		"Mana": "215",
		"Mana_Per_Level": "40",
		"Speed": "310",
		"Range": "125",
		"Attack_Speed": "0.638",
		"AS_Per_Level": "0.021",
		"Armor": "18",
		"Armor_Per_Level": "3.75",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.45",
		"HR_Per_level": "0.55",
		"Mana_regen": "6.4",
		"MRegen_Per_Level": "0.55",
		"Tags": "Fighter, melee",
		"Champ_Id": "54",
		"Release_Date": "2009-09-02"
	},
	{
		"Name": "Malzahar",
		"Title": "The Prophet of the Void",
		"Rp_Point": "975",
		"Ip_Point": "4800",
		"Damage": "51.66",
		"Damage_per_level": "3",
		"Health": "380",
		"Health_Per_level": "80",
		"Mana": "250",
		"Mana_Per_Level": "45",
		"Speed": "315",
		"Range": "550",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.0085",
		"Armor": "15",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.5",
		"HR_Per_level": "0.55",
		"Mana_regen": "7.0",
		"MRegen_Per_Level": "0.6",
		"Tags": "Mage, ranged",
		"Champ_Id": "90",
		"Release_Date": "2010-06-01"
	},
	{
		"Name": "Maokai",
		"Title": "The Twisted Treant",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "58",
		"Damage_per_level": "3.3",
		"Health": "421",
		"Health_Per_level": "90",
		"Mana": "250",
		"Mana_Per_Level": "46",
		"Speed": "310",
		"Range": "125",
		"Attack_Speed": "0.694",
		"AS_Per_Level": "0.0145",
		"Armor": "18",
		"Armor_Per_Level": "4",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "7.25",
		"HR_Per_level": "0.85",
		"Mana_regen": "6.45",
		"MRegen_Per_Level": "0.45",
		"Tags": "Tank, pusher, melee",
		"Champ_Id": "57",
		"Release_Date": "2011-02-16"
	},
	{
		"Name": "Master Yi",
		"Title": "The Wuju Bladesman",
		"Rp_Point": "260",
		"Ip_Point": "450",
		"Damage": "55.12",
		"Damage_per_level": "3.1",
		"Health": "444",
		"Health_Per_level": "86",
		"Mana": "199",
		"Mana_Per_Level": "36",
		"Speed": "330",
		"Range": "125",
		"Attack_Speed": "0.679",
		"AS_Per_Level": "0.02",
		"Armor": "16.3",
		"Armor_Per_Level": "3.7",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "6.75",
		"HR_Per_level": "0.65",
		"Mana_regen": "6.5",
		"MRegen_Per_Level": "0.45",
		"Tags": "Carry, melee, recommended",
		"Champ_Id": "11",
		"Release_Date": "2009-02-21"
	},
	{
		"Name": "Miss Fortune",
		"Title": "The Bounty Hunter",
		"Rp_Point": "975",
		"Ip_Point": "4800",
		"Damage": "46.5",
		"Damage_per_level": "3",
		"Health": "435",
		"Health_Per_level": "85",
		"Mana": "212",
		"Mana_Per_Level": "38",
		"Speed": "300",
		"Range": "550",
		"Attack_Speed": "0.656",
		"AS_Per_Level": "0.02",
		"Armor": "15",
		"Armor_Per_Level": "3",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "5.1",
		"HR_Per_level": "0.65",
		"Mana_regen": "6.95",
		"MRegen_Per_Level": "0.65",
		"Tags": "Ranged, carry",
		"Champ_Id": "21",
		"Release_Date": "2010-09-08"
	},
	{
		"Name": "Mordekaiser",
		"Title": "the Master of Metal",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "51.7",
		"Damage_per_level": "3.5",
		"Health": "421",
		"Health_Per_level": "80",
		"Mana": "0",
		"Mana_Per_Level": "0",
		"Speed": "315",
		"Range": "125",
		"Attack_Speed": "0.694",
		"AS_Per_Level": "0.021",
		"Armor": "15",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.45",
		"HR_Per_level": "0.55",
		"Mana_regen": "0",
		"MRegen_Per_Level": "0",
		"Tags": "Fighter, pusher, melee",
		"Champ_Id": "82",
		"Release_Date": "2010-02-24"
	},
	{
		"Name": "Morgana",
		"Title": "Fallen Angel",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "51.58",
		"Damage_per_level": "3.5",
		"Health": "403",
		"Health_Per_level": "86",
		"Mana": "240",
		"Mana_Per_Level": "60",
		"Speed": "310",
		"Range": "425",
		"Attack_Speed": "0.579",
		"AS_Per_Level": "0.0085",
		"Armor": "15",
		"Armor_Per_Level": "3.8",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.7",
		"HR_Per_level": "0.6",
		"Mana_regen": "6.8",
		"MRegen_Per_Level": "0.65",
		"Tags": "Mage, support, ranged",
		"Champ_Id": "25",
		"Release_Date": "2009-02-21"
	},
	{
		"Name": "Nasus",
		"Title": "The Curator of the Sands",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "53.3",
		"Damage_per_level": "3.5",
		"Health": "410",
		"Health_Per_level": "90",
		"Mana": "200",
		"Mana_Per_Level": "45",
		"Speed": "325",
		"Range": "125",
		"Attack_Speed": "0.638",
		"AS_Per_Level": "0.022",
		"Armor": "15",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.5",
		"HR_Per_level": "0.9",
		"Mana_regen": "6.6",
		"MRegen_Per_Level": "0.5",
		"Tags": "Fighter, pusher, melee, recommended",
		"Champ_Id": "75",
		"Release_Date": "2009-10-01"
	},
	{
		"Name": "Nautilus",
		"Title": "The Titan of the Depths",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "52",
		"Damage_per_level": "3.3",
		"Health": "432",
		"Health_Per_level": "86",
		"Mana": "200",
		"Mana_Per_Level": "50",
		"Speed": "300",
		"Range": "175",
		"Attack_Speed": "0.613",
		"AS_Per_Level": "0.006",
		"Armor": "12",
		"Armor_Per_Level": "3.25",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.45",
		"HR_Per_level": "0.55",
		"Mana_regen": "7.45",
		"MRegen_Per_Level": "0.7",
		"Tags": "Fighter, melee",
		"Champ_Id": "113",
		"Release_Date": "2012-02-14"
	},
	{
		"Name": "Nidalee",
		"Title": "The Bestial Huntress",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "49",
		"Damage_per_level": "3.5",
		"Health": "370",
		"Health_Per_level": "90",
		"Mana": "220",
		"Mana_Per_Level": "45",
		"Speed": "310",
		"Range": "525",
		"Attack_Speed": "0.670",
		"AS_Per_Level": "0.0216",
		"Armor": "11",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "0.75",
		"Health_Regen": "5.0",
		"HR_Per_level": "0.6",
		"Mana_regen": "7.0",
		"MRegen_Per_Level": "0.5",
		"Tags": "Support, pusher",
		"Champ_Id": "76",
		"Release_Date": "2009-12-17"
	},
	{
		"Name": "Nocturne",
		"Title": "The Eternal Nightmare",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "54",
		"Damage_per_level": "3.1",
		"Health": "430",
		"Health_Per_level": "85",
		"Mana": "215",
		"Mana_Per_Level": "35",
		"Speed": "320",
		"Range": "125",
		"Attack_Speed": "0.640",
		"AS_Per_Level": "0.018",
		"Armor": "17",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.0",
		"HR_Per_level": "0.75",
		"Mana_regen": "6.0",
		"MRegen_Per_Level": "0.45",
		"Tags": "Assassin, melee",
		"Champ_Id": "56",
		"Release_Date": "2011-03-16"
	},
	{
		"Name": "Nunu",
		"Title": "The Yeti Rider",
		"Rp_Point": "260",
		"Ip_Point": "450",
		"Damage": "51.6",
		"Damage_per_level": "3.4",
		"Health": "437",
		"Health_Per_level": "108",
		"Mana": "213",
		"Mana_Per_Level": "42",
		"Speed": "315",
		"Range": "125",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.0067",
		"Armor": "16.5",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.05",
		"HR_Per_level": "0.8",
		"Mana_regen": "6.6",
		"MRegen_Per_Level": "0.5",
		"Tags": "Fighter, melee, jungler, recommended",
		"Champ_Id": "20",
		"Release_Date": "2009-02-21"
	},
	{
		"Name": "Olaf",
		"Title": "The Berserker",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "54.1",
		"Damage_per_level": "3.5",
		"Health": "441",
		"Health_Per_level": "93",
		"Mana": "225",
		"Mana_Per_Level": "45",
		"Speed": "325",
		"Range": "125",
		"Attack_Speed": "0.694",
		"AS_Per_Level": "0.021",
		"Armor": "17",
		"Armor_Per_Level": "3",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.0",
		"HR_Per_level": "0.9",
		"Mana_regen": "6.5",
		"MRegen_Per_Level": "0.575",
		"Tags": "Fighter, melee",
		"Champ_Id": "2",
		"Release_Date": "2010-06-09"
	},
	{
		"Name": "Orianna",
		"Title": "The Lady of Clockwork",
		"Rp_Point": "975",
		"Ip_Point": "4800",
		"Damage": "44",
		"Damage_per_level": "2.6",
		"Health": "385",
		"Health_Per_level": "79",
		"Mana": "250",
		"Mana_Per_Level": "50",
		"Speed": "300",
		"Range": "525",
		"Attack_Speed": "0.658",
		"AS_Per_Level": "0.023",
		"Armor": "8",
		"Armor_Per_Level": "3",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "5.95",
		"HR_Per_level": "0.55",
		"Mana_regen": "7.0",
		"MRegen_Per_Level": "0.5",
		"Tags": "Mage, ranged",
		"Champ_Id": "61",
		"Release_Date": "2011-06-01"
	},
	{
		"Name": "Pantheon",
		"Title": "The Artisan of War",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "50.7",
		"Damage_per_level": "2.9",
		"Health": "433",
		"Health_Per_level": "87",
		"Mana": "210",
		"Mana_Per_Level": "34",
		"Speed": "330",
		"Range": "150",
		"Attack_Speed": "0.679",
		"AS_Per_Level": "0.02",
		"Armor": "17.1",
		"Armor_Per_Level": "3.9",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "6.75",
		"HR_Per_level": "0.65",
		"Mana_regen": "6.6",
		"MRegen_Per_Level": "0.45",
		"Tags": "Assassin, melee",
		"Champ_Id": "80",
		"Release_Date": "2010-02-02"
	},
	{
		"Name": "Poppy",
		"Title": "The Iron Ambassador",
		"Rp_Point": "260",
		"Ip_Point": "450",
		"Damage": "56.3",
		"Damage_per_level": "3.375",
		"Health": "423",
		"Health_Per_level": "81",
		"Mana": "185",
		"Mana_Per_Level": "30",
		"Speed": "320",
		"Range": "125",
		"Attack_Speed": "0.638",
		"AS_Per_Level": "0.0212",
		"Armor": "18",
		"Armor_Per_Level": "4",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "7.45",
		"HR_Per_level": "0.55",
		"Mana_regen": "6.4",
		"MRegen_Per_Level": "0.45",
		"Tags": "Fighter, assassin, melee",
		"Champ_Id": "78",
		"Release_Date": "2010-01-13"
	},
	{
		"Name": "Rammus",
		"Title": "The Armordillo",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "50",
		"Damage_per_level": "3.5",
		"Health": "420",
		"Health_Per_level": "86",
		"Mana": "255",
		"Mana_Per_Level": "33",
		"Speed": "310",
		"Range": "125",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.014",
		"Armor": "17",
		"Armor_Per_Level": "3.8",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "5",
		"HR_Per_level": "0.55",
		"Mana_regen": "4.5",
		"MRegen_Per_Level": "0.3",
		"Tags": "Tank, melee, recommended",
		"Champ_Id": "33",
		"Release_Date": "2009-07-10"
	},
	{
		"Name": "Renekton",
		"Title": "The Butcher of the Sands",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "53.12",
		"Damage_per_level": "3.1",
		"Health": "429",
		"Health_Per_level": "87",
		"Mana": "100",
		"Mana_Per_Level": "0",
		"Speed": "320",
		"Range": "125",
		"Attack_Speed": "0.665",
		"AS_Per_Level": "0.01762",
		"Armor": "15.2",
		"Armor_Per_Level": "3.8",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "6.7",
		"HR_Per_level": "0.75",
		"Mana_regen": "0",
		"MRegen_Per_Level": "0",
		"Tags": "Fighter, melee",
		"Champ_Id": "58",
		"Release_Date": "2011-01-19"
	},
	{
		"Name": "Rengar",
		"Title": "The Pridestalker",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "55",
		"Damage_per_level": "3",
		"Health": "435",
		"Health_Per_level": "85",
		"Mana": "5",
		"Mana_Per_Level": "0",
		"Speed": "320",
		"Range": "125",
		"Attack_Speed": "0.675",
		"AS_Per_Level": "0.019",
		"Armor": "16",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.05",
		"HR_Per_level": "0.8",
		"Mana_regen": "30",
		"MRegen_Per_Level": "1.25",
		"Tags": "Melee,stealth,fighter,jungler",
		"Champ_Id": "123",
		"Release_Date": "2012-08-21"
	},
	{
		"Name": "Riven",
		"Title": "The Exile",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "54",
		"Damage_per_level": "2.75",
		"Health": "414",
		"Health_Per_level": "86",
		"Mana": "0",
		"Mana_Per_Level": "0",
		"Speed": "320",
		"Range": "125",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.018125",
		"Armor": "15",
		"Armor_Per_Level": "3.1",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "10.4",
		"HR_Per_level": "0.9",
		"Mana_regen": "0",
		"MRegen_Per_Level": "0",
		"Tags": "Fighter, melee",
		"Champ_Id": "101",
		"Release_Date": "2011-09-14"
	},
	{
		"Name": "Rumble",
		"Title": "The Mechanized Menace",
		"Rp_Point": "975",
		"Ip_Point": "4800",
		"Damage": "55.66",
		"Damage_per_level": "3.2",
		"Health": "450",
		"Health_Per_level": "80",
		"Mana": "100",
		"Mana_Per_Level": "0",
		"Speed": "320",
		"Range": "125",
		"Attack_Speed": "0.632",
		"AS_Per_Level": "0.012",
		"Armor": "16",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.0",
		"HR_Per_level": "0.7",
		"Mana_regen": "0",
		"MRegen_Per_Level": "0",
		"Tags": "Mage, Melee, Pusher",
		"Champ_Id": "68",
		"Release_Date": "2011-04-26"
	},
	{
		"Name": "Ryze",
		"Title": "The Rogue Mage",
		"Rp_Point": "260",
		"Ip_Point": "450",
		"Damage": "52",
		"Damage_per_level": "3",
		"Health": "360",
		"Health_Per_level": "86",
		"Mana": "250",
		"Mana_Per_Level": "55",
		"Speed": "310",
		"Range": "550",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.0132",
		"Armor": "11",
		"Armor_Per_Level": "3.9",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.35",
		"HR_Per_level": "0.55",
		"Mana_regen": "7.0",
		"MRegen_Per_Level": "0.6",
		"Tags": "Mage, ranged, recommended",
		"Champ_Id": "13",
		"Release_Date": "2009-02-21"
	},
	{
		"Name": "Sejuani",
		"Title": "The Winter's Wrath",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "54",
		"Damage_per_level": "3.4",
		"Health": "450",
		"Health_Per_level": "85",
		"Mana": "220",
		"Mana_Per_Level": "40",
		"Speed": "315",
		"Range": "125",
		"Attack_Speed": "0.694",
		"AS_Per_Level": "0.021",
		"Armor": "17.5",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.25",
		"HR_Per_level": "0.85",
		"Mana_regen": "6.45",
		"MRegen_Per_Level": "0.45",
		"Tags": "Tank, jungler, melee",
		"Champ_Id": "111",
		"Release_Date": "2012-01-17"
	},
	{
		"Name": "Shaco",
		"Title": "The Demon Jester",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "51.7",
		"Damage_per_level": "3.5",
		"Health": "441",
		"Health_Per_level": "84",
		"Mana": "270",
		"Mana_Per_Level": "40",
		"Speed": "325",
		"Range": "125",
		"Attack_Speed": "0.694",
		"AS_Per_Level": "0.021",
		"Armor": "15",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.45",
		"HR_Per_level": "0.55",
		"Mana_regen": "6.4",
		"MRegen_Per_Level": "0.45",
		"Tags": "Assassin, stealth, melee",
		"Champ_Id": "35",
		"Release_Date": "2009-10-10"
	},
	{
		"Name": "Shen",
		"Title": "The Eye of Twilight",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "54.5",
		"Damage_per_level": "3.375",
		"Health": "428",
		"Health_Per_level": "85",
		"Mana": "200",
		"Mana_Per_Level": "0",
		"Speed": "310",
		"Range": "125",
		"Attack_Speed": "0.651",
		"AS_Per_Level": "0.022",
		"Armor": "19",
		"Armor_Per_Level": "4",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "7.45",
		"HR_Per_level": "0.55",
		"Mana_regen": "50",
		"MRegen_Per_Level": "0",
		"Tags": "Tank, support, melee",
		"Champ_Id": "98",
		"Release_Date": "2010-03-24"
	},
	{
		"Name": "Shyvana",
		"Title": "The Half-Dragon",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "54.5",
		"Damage_per_level": "3.4",
		"Health": "435",
		"Health_Per_level": "95",
		"Mana": "0",
		"Mana_Per_Level": "0",
		"Speed": "325",
		"Range": "125",
		"Attack_Speed": "0.656",
		"AS_Per_Level": "0.025",
		"Armor": "17.6",
		"Armor_Per_Level": "3.4",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.2",
		"HR_Per_level": "0.8",
		"Mana_regen": "0",
		"MRegen_Per_Level": "0",
		"Tags": "Fighter, melee",
		"Champ_Id": "106",
		"Release_Date": "2011-11-01"
	},
	{
		"Name": "Singed",
		"Title": "Mad Chemist",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "56.65",
		"Damage_per_level": "3.375",
		"Health": "405",
		"Health_Per_level": "82",
		"Mana": "215",
		"Mana_Per_Level": "45",
		"Speed": "320",
		"Range": "125",
		"Attack_Speed": "0.613",
		"AS_Per_Level": "0.011",
		"Armor": "18",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "7.1",
		"HR_Per_level": "0.55",
		"Mana_regen": "6.6",
		"MRegen_Per_Level": "0.55",
		"Tags": "Fighter, melee",
		"Champ_Id": "27",
		"Release_Date": "2009-04-18"
	},
	{
		"Name": "Sion",
		"Title": "The Undead Champion",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "55.52",
		"Damage_per_level": "3.1875",
		"Health": "403",
		"Health_Per_level": "104",
		"Mana": "240",
		"Mana_Per_Level": "40",
		"Speed": "320",
		"Range": "125",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.01",
		"Armor": "17.75",
		"Armor_Per_Level": "3.25",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.9",
		"HR_Per_level": "0.95",
		"Mana_regen": "6.3",
		"MRegen_Per_Level": "0.4",
		"Tags": "Fighter, melee",
		"Champ_Id": "14",
		"Release_Date": "2009-02-21"
	},
	{
		"Name": "Sivir",
		"Title": "The Battle Mistress",
		"Rp_Point": "260",
		"Ip_Point": "450",
		"Damage": "49",
		"Damage_per_level": "2.9",
		"Health": "384",
		"Health_Per_level": "82",
		"Mana": "203",
		"Mana_Per_Level": "43",
		"Speed": "310",
		"Range": "500",
		"Attack_Speed": "0.658",
		"AS_Per_Level": "0.021",
		"Armor": "12.75",
		"Armor_Per_Level": "3.25",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.25",
		"HR_Per_level": "0.55",
		"Mana_regen": "6.5",
		"MRegen_Per_Level": "0.5",
		"Tags": "Carry, pusher, ranged, recommended",
		"Champ_Id": "15",
		"Release_Date": "2009-02-21"
	},
	{
		"Name": "Skarner",
		"Title": "The Crystal Vanguard",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "54.1",
		"Damage_per_level": "4.2",
		"Health": "440",
		"Health_Per_level": "96",
		"Mana": "205",
		"Mana_Per_Level": "40",
		"Speed": "320",
		"Range": "125",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.0131",
		"Armor": "19",
		"Armor_Per_Level": "3.8",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.5",
		"HR_Per_level": "0.85",
		"Mana_regen": "6.45",
		"MRegen_Per_Level": "0.45",
		"Tags": "Fighter, jungler, melee",
		"Champ_Id": "102",
		"Release_Date": "2011-08-09"
	},
	{
		"Name": "Sona",
		"Title": "The Maven of the Strings",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "47",
		"Damage_per_level": "3",
		"Health": "380",
		"Health_Per_level": "70",
		"Mana": "265",
		"Mana_Per_Level": "45",
		"Speed": "305",
		"Range": "550",
		"Attack_Speed": "0.644",
		"AS_Per_Level": "0.015",
		"Armor": "8",
		"Armor_Per_Level": "3.3",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.5",
		"HR_Per_level": "0.55",
		"Mana_regen": "7.0",
		"MRegen_Per_Level": "0.65",
		"Tags": "Support, ranged, recommended",
		"Champ_Id": "37",
		"Release_Date": "2010-09-20"
	},
	{
		"Name": "Soraka",
		"Title": "The Starchild",
		"Rp_Point": "260",
		"Ip_Point": "450",
		"Damage": "48.8",
		"Damage_per_level": "3",
		"Health": "375",
		"Health_Per_level": "71",
		"Mana": "240",
		"Mana_Per_Level": "60",
		"Speed": "310",
		"Range": "550",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.0133",
		"Armor": "7.4",
		"Armor_Per_Level": "3.8",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.5",
		"HR_Per_level": "0.55",
		"Mana_regen": "4.3",
		"MRegen_Per_Level": "0.45",
		"Tags": "Support, ranged, recommended",
		"Champ_Id": "16",
		"Release_Date": "2009-02-21"
	},
	{
		"Name": "Swain",
		"Title": "The Master Tactician",
		"Rp_Point": "975",
		"Ip_Point": "4800",
		"Damage": "49",
		"Damage_per_level": "3",
		"Health": "385",
		"Health_Per_level": "78",
		"Mana": "240",
		"Mana_Per_Level": "50",
		"Speed": "310",
		"Range": "500",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.013",
		"Armor": "12",
		"Armor_Per_Level": "4",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "6.75",
		"HR_Per_level": "0.65",
		"Mana_regen": "6.8",
		"MRegen_Per_Level": "0.65",
		"Tags": "Mage, ranged",
		"Champ_Id": "50",
		"Release_Date": "2010-10-05"
	},
	{
		"Name": "Talon",
		"Title": "The Blade's Shadow",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "50",
		"Damage_per_level": "3.1",
		"Health": "440",
		"Health_Per_level": "85",
		"Mana": "260",
		"Mana_Per_Level": "40",
		"Speed": "325",
		"Range": "125",
		"Attack_Speed": "0.668",
		"AS_Per_Level": "0.018",
		"Armor": "12",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.25",
		"HR_Per_level": "0.75",
		"Mana_regen": "6.75",
		"MRegen_Per_Level": "0.5",
		"Tags": "Assassin, melee",
		"Champ_Id": "100",
		"Release_Date": "2011-08-24"
	},
	{
		"Name": "Taric",
		"Title": "The Gem Knight",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "58",
		"Damage_per_level": "3.5",
		"Health": "468",
		"Health_Per_level": "90",
		"Mana": "255",
		"Mana_Per_Level": "56",
		"Speed": "315",
		"Range": "125",
		"Attack_Speed": "0.613",
		"AS_Per_Level": "0.012",
		"Armor": "16.5",
		"Armor_Per_Level": "3.2",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.1",
		"HR_Per_level": "0.5",
		"Mana_regen": "4.1",
		"MRegen_Per_Level": "0.4",
		"Tags": "Tank, support, melee, recommended",
		"Champ_Id": "44",
		"Release_Date": "2009-08-19"
	},
	{
		"Name": "Teemo",
		"Title": "The Swift Scout",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "44.5",
		"Damage_per_level": "3",
		"Health": "383",
		"Health_Per_level": "82",
		"Mana": "200",
		"Mana_Per_Level": "40",
		"Speed": "305",
		"Range": "500",
		"Attack_Speed": "0.690",
		"AS_Per_Level": "0.0235",
		"Armor": "14",
		"Armor_Per_Level": "3.75",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.65",
		"HR_Per_level": "0.65",
		"Mana_regen": "6.5",
		"MRegen_Per_Level": "0",
		"Tags": "Support, stealth, ranged",
		"Champ_Id": "17",
		"Release_Date": "2009-02-21"
	},
	{
		"Name": "Tristana",
		"Title": "The Megling Gunner",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "46.5",
		"Damage_per_level": "3",
		"Health": "415",
		"Health_Per_level": "82",
		"Mana": "193",
		"Mana_Per_Level": "32",
		"Speed": "300",
		"Range": "550",
		"Attack_Speed": "0.656",
		"AS_Per_Level": "0.02",
		"Armor": "15",
		"Armor_Per_Level": "3",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "5.1",
		"HR_Per_level": "0.65",
		"Mana_regen": "3.95",
		"MRegen_Per_Level": "0.25",
		"Tags": "Carry, ranged, recommended",
		"Champ_Id": "18",
		"Release_Date": "2009-02-21"
	},
	{
		"Name": "Trundle",
		"Title": "The Cursed Troll",
		"Rp_Point": "975",
		"Ip_Point": "4800",
		"Damage": "54.66",
		"Damage_per_level": "3",
		"Health": "455",
		"Health_Per_level": "96",
		"Mana": "206",
		"Mana_Per_Level": "45",
		"Speed": "325",
		"Range": "125",
		"Attack_Speed": "0.650",
		"AS_Per_Level": "0.012",
		"Armor": "19",
		"Armor_Per_Level": "2.7",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "8.0",
		"HR_Per_level": "0.85",
		"Mana_regen": "6.9",
		"MRegen_Per_Level": "0.6",
		"Tags": "Fighter, melee",
		"Champ_Id": "48",
		"Release_Date": "2010-12-01"
	},
	{
		"Name": "Tryndamere",
		"Title": "The Babarian King",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "56",
		"Damage_per_level": "3.2",
		"Health": "461",
		"Health_Per_level": "98",
		"Mana": "0",
		"Mana_Per_Level": "0",
		"Speed": "320",
		"Range": "125",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.018",
		"Armor": "14.9",
		"Armor_Per_Level": "3.1",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.9",
		"HR_Per_level": "0.9",
		"Mana_regen": "0",
		"MRegen_Per_Level": "0",
		"Tags": "Carry, melee",
		"Champ_Id": "23",
		"Release_Date": "2009-05-01"
	},
	{
		"Name": "Twisted Fate",
		"Title": "The Card Master",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "46.41",
		"Damage_per_level": "3.3",
		"Health": "384",
		"Health_Per_level": "82",
		"Mana": "202",
		"Mana_Per_Level": "38",
		"Speed": "305",
		"Range": "525",
		"Attack_Speed": "0.651",
		"AS_Per_Level": "0.021",
		"Armor": "11.25",
		"Armor_Per_Level": "3.2",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.5",
		"HR_Per_level": "0.6",
		"Mana_regen": "4.0",
		"MRegen_Per_Level": "0.3",
		"Tags": "Assassin, pusher, ranged",
		"Champ_Id": "4",
		"Release_Date": "2009-02-21"
	},
	{
		"Name": "Twitch",
		"Title": "The Plague Rat",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "49",
		"Damage_per_level": "3",
		"Health": "389",
		"Health_Per_level": "81",
		"Mana": "220",
		"Mana_Per_Level": "40",
		"Speed": "305",
		"Range": "550",
		"Attack_Speed": "0.679",
		"AS_Per_Level": "0.025",
		"Armor": "14",
		"Armor_Per_Level": "3",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "5.1",
		"HR_Per_level": "0.65",
		"Mana_regen": "3.95",
		"MRegen_Per_Level": "0.25",
		"Tags": "Carry, stealth, ranged",
		"Champ_Id": "29",
		"Release_Date": "2009-05-01"
	},
	{
		"Name": "Udyr",
		"Title": "The Animal Spirit",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "52.91",
		"Damage_per_level": "3.2",
		"Health": "427",
		"Health_Per_level": "99",
		"Mana": "220",
		"Mana_Per_Level": "30",
		"Speed": "320",
		"Range": "125",
		"Attack_Speed": "0.658",
		"AS_Per_Level": "0.017",
		"Armor": "14.75",
		"Armor_Per_Level": "4",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.45",
		"HR_Per_level": "0.75",
		"Mana_regen": "6.4",
		"MRegen_Per_Level": "0.45",
		"Tags": "Fighter, melee",
		"Champ_Id": "77",
		"Release_Date": "2009-12-02"
	},
	{
		"Name": "Urgot",
		"Title": "The Headman's Pride",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "48",
		"Damage_per_level": "3.6",
		"Health": "437",
		"Health_Per_level": "89",
		"Mana": "220",
		"Mana_Per_Level": "55",
		"Speed": "310",
		"Range": "425",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.017",
		"Armor": "15",
		"Armor_Per_Level": "3.3",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "5.5",
		"HR_Per_level": "0.6",
		"Mana_regen": "7.5",
		"MRegen_Per_Level": "0.65",
		"Tags": "Fighter, ranged",
		"Champ_Id": "6",
		"Release_Date": "2010-08-24"
	},
	{
		"Name": "Varus",
		"Title": "The Arrow of Retribution",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "46",
		"Damage_per_level": "3",
		"Health": "400",
		"Health_Per_level": "82",
		"Mana": "250",
		"Mana_Per_Level": "36",
		"Speed": "310",
		"Range": "575",
		"Attack_Speed": "0.658",
		"AS_Per_Level": "0.017",
		"Armor": "13.5",
		"Armor_Per_Level": "3.4",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.5",
		"HR_Per_level": "0.55",
		"Mana_regen": "6.5",
		"MRegen_Per_Level": "0.5",
		"Tags": "Carry, ranged",
		"Champ_Id": "117",
		"Release_Date": "2012-05-08"
	},
	{
		"Name": "Vayne",
		"Title": "The Night Hunter",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "50",
		"Damage_per_level": "3.25",
		"Health": "359",
		"Health_Per_level": "83",
		"Mana": "173",
		"Mana_Per_Level": "27",
		"Speed": "300",
		"Range": "550",
		"Attack_Speed": "0.658",
		"AS_Per_Level": "0.022",
		"Armor": "9.3",
		"Armor_Per_Level": "3.4",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.5",
		"HR_Per_level": "0.55",
		"Mana_regen": "6.3",
		"MRegen_Per_Level": "0.4",
		"Tags": "Carry, ranged, assassin, stealth",
		"Champ_Id": "67",
		"Release_Date": "2011-05-10"
	},
	{
		"Name": "Veigar",
		"Title": "The Tiny Master of Evil",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "48.3",
		"Damage_per_level": "2.625",
		"Health": "355",
		"Health_Per_level": "82",
		"Mana": "250",
		"Mana_Per_Level": "55",
		"Speed": "315",
		"Range": "525",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.014",
		"Armor": "12.25",
		"Armor_Per_Level": "3.75",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.5",
		"HR_Per_level": "0.55",
		"Mana_regen": "6.9",
		"MRegen_Per_Level": "0.60",
		"Tags": "Mage, ranged",
		"Champ_Id": "45",
		"Release_Date": "2009-07-24"
	},
	{
		"Name": "Viktor",
		"Title": "The Machine Herald",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "49",
		"Damage_per_level": "3",
		"Health": "385",
		"Health_Per_level": "78",
		"Mana": "240",
		"Mana_Per_Level": "50",
		"Speed": "310",
		"Range": "525",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.013",
		"Armor": "12",
		"Armor_Per_Level": "4",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "6.75",
		"HR_Per_level": "0.65",
		"Mana_regen": "6.9",
		"MRegen_Per_Level": "0.45",
		"Tags": "Mage, ranged, pusher",
		"Champ_Id": "110",
		"Release_Date": "2011-12-28"
	},
	{
		"Name": "Vladimir",
		"Title": "The Crimson Reaper",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "45",
		"Damage_per_level": "3",
		"Health": "400",
		"Health_Per_level": "85",
		"Mana": "0",
		"Mana_Per_Level": "0",
		"Speed": "310",
		"Range": "450",
		"Attack_Speed": "0.658",
		"AS_Per_Level": "0.013",
		"Armor": "12",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "6.0",
		"HR_Per_level": "0.6",
		"Mana_regen": "0",
		"MRegen_Per_Level": "0",
		"Tags": "Fighter, mage, ranged",
		"Champ_Id": "8",
		"Release_Date": "2010-07-27"
	},
	{
		"Name": "Volibear",
		"Title": "The Thunder's Roar",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "54",
		"Damage_per_level": "3.3",
		"Health": "440",
		"Health_Per_level": "86",
		"Mana": "220",
		"Mana_Per_Level": "30",
		"Speed": "320",
		"Range": "125",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.018",
		"Armor": "20",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.0",
		"HR_Per_level": "0.65",
		"Mana_regen": "7.0",
		"MRegen_Per_Level": "0.65",
		"Tags": "Tank, fighter, jungler, melee",
		"Champ_Id": "107",
		"Release_Date": "2011-11-29"
	},
	{
		"Name": "Warwick",
		"Title": "The Blood Hunter",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "56.76",
		"Damage_per_level": "3.375",
		"Health": "428",
		"Health_Per_level": "98",
		"Mana": "190",
		"Mana_Per_Level": "30",
		"Speed": "320",
		"Range": "125",
		"Attack_Speed": "0.679",
		"AS_Per_Level": "0.019",
		"Armor": "16",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.05",
		"HR_Per_level": "0.8",
		"Mana_regen": "7.1",
		"MRegen_Per_Level": "0.6",
		"Tags": "Fighter, jungler, melee, recommended",
		"Champ_Id": "19",
		"Release_Date": "2009-02-21"
	},
	{
		"Name": "Wukong",
		"Title": "The Monkey King",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "54",
		"Damage_per_level": "3.2",
		"Health": "435",
		"Health_Per_level": "85",
		"Mana": "202",
		"Mana_Per_Level": "38",
		"Speed": "320",
		"Range": "175",
		"Attack_Speed": "0.658",
		"AS_Per_Level": "0.03",
		"Armor": "15",
		"Armor_Per_Level": "3.5",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "5.1",
		"HR_Per_level": "0.65",
		"Mana_regen": "6.9",
		"MRegen_Per_Level": "0.65",
		"Tags": "Fighter, melee, stealth",
		"Champ_Id": "103",
		"Release_Date": "2011-07-26"
	},
	{
		"Name": "Xerath",
		"Title": "The Magus Ascendant",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "52",
		"Damage_per_level": "3",
		"Health": "380",
		"Health_Per_level": "80",
		"Mana": "250",
		"Mana_Per_Level": "45",
		"Speed": "315",
		"Range": "550",
		"Attack_Speed": "0.63",
		"AS_Per_Level": "0.008",
		"Armor": "12.6",
		"Armor_Per_Level": "3.4",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "5.0",
		"HR_Per_level": "0.53",
		"Mana_regen": "8.0",
		"MRegen_Per_Level": "0.6",
		"Tags": "Mage, ranged",
		"Champ_Id": "104",
		"Release_Date": "2011-10-05"
	},
	{
		"Name": "Xin Zhao",
		"Title": "The Seneschal of Demacia",
		"Rp_Point": "975",
		"Ip_Point": "3150",
		"Damage": "52",
		"Damage_per_level": "3.3",
		"Health": "445",
		"Health_Per_level": "87",
		"Mana": "213",
		"Mana_Per_Level": "31",
		"Speed": "320",
		"Range": "175",
		"Attack_Speed": "0.672",
		"AS_Per_Level": "0.0181",
		"Armor": "16.2",
		"Armor_Per_Level": "3.7",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "7.0",
		"HR_Per_level": "0.7",
		"Mana_regen": "6.6",
		"MRegen_Per_Level": "0.45",
		"Tags": "Fighter, assassin, melee",
		"Champ_Id": "5",
		"Release_Date": "2010-07-13"
	},
	{
		"Name": "Yorick",
		"Title": "The Gravedigger",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "51.5",
		"Damage_per_level": "3.5",
		"Health": "421",
		"Health_Per_level": "85",
		"Mana": "265",
		"Mana_Per_Level": "35",
		"Speed": "320",
		"Range": "125",
		"Attack_Speed": "0.658",
		"AS_Per_Level": "0.03",
		"Armor": "18",
		"Armor_Per_Level": "3.6",
		"Magic_Resistance": "30",
		"MR_Per_level": "1.25",
		"Health_Regen": "8.5",
		"HR_Per_level": "0.70",
		"Mana_regen": "6.5",
		"MRegen_Per_Level": "0.45",
		"Tags": "Fighter, pusher, melee",
		"Champ_Id": "83",
		"Release_Date": "2011-06-22"
	},
	{
		"Name": "Ziggs",
		"Title": "The Hexplosives Expert",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "51",
		"Damage_per_level": "3.1",
		"Health": "390",
		"Health_Per_level": "80",
		"Mana": "250",
		"Mana_Per_Level": "50",
		"Speed": "305",
		"Range": "575",
		"Attack_Speed": "0.656",
		"AS_Per_Level": "0.011",
		"Armor": "12",
		"Armor_Per_Level": "3.3",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "5.25",
		"HR_Per_level": "0.6",
		"Mana_regen": "6.75",
		"MRegen_Per_Level": "0.6",
		"Tags": "Mage, ranged, pusher",
		"Champ_Id": "112",
		"Release_Date": "2012-02-01"
	},
	{
		"Name": "Zilean",
		"Title": "The Chronokeeper",
		"Rp_Point": "585",
		"Ip_Point": "1350",
		"Damage": "48.6",
		"Damage_per_level": "3",
		"Health": "380",
		"Health_Per_level": "71",
		"Mana": "260",
		"Mana_Per_Level": "60",
		"Speed": "310",
		"Range": "600",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.013",
		"Armor": "6.75",
		"Armor_Per_Level": "3.8",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.6",
		"HR_Per_level": "0.5",
		"Mana_regen": "6.95",
		"MRegen_Per_Level": "0.65",
		"Tags": "Mage, support, ranged",
		"Champ_Id": "26",
		"Release_Date": "2009-04-18"
	},
	{
		"Name": "Zyra",
		"Title": "The Rise of the Thorns",
		"Rp_Point": "975",
		"Ip_Point": "6300",
		"Damage": "50",
		"Damage_per_level": "3.2",
		"Health": "355",
		"Health_Per_level": "74",
		"Mana": "250",
		"Mana_Per_Level": "50",
		"Speed": "300",
		"Range": "575",
		"Attack_Speed": "0.625",
		"AS_Per_Level": "0.011",
		"Armor": "11",
		"Armor_Per_Level": "3",
		"Magic_Resistance": "30",
		"MR_Per_level": "0",
		"Health_Regen": "4.85",
		"HR_Per_level": "0.5",
		"Mana_regen": "7.1",
		"MRegen_Per_Level": "0.75",
		"Tags": "Mage, pusher, ranged",
		"Champ_Id": "121",
		"Release_Date": "2012-07-24"
	}];

return Champions;
});